services:
  - type: web
    name: rhyme-for-christ
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
    autoDeploy: true